apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-website
spec:
  replicas: 1
  selector:
    matchLabels:
      name: my-app
  template:
    metadata:
      labels:
        name: my-app
    spec:
      containers:
      - name: my-app
        image: milansuras/website:v1

