apiVersion: v1
kind: Pod
metadata: 
 name: config-map-pod
spec:
  containers:
    - name: configmaptest
      image: ubuntu
      command: ["bash",'-c',echo '"The app running" && tail -f /dev/null']
      volumeMounts:
        - name: config-vol
          mountPath: /etc/config
  volumes:
    - name: config-vol
      configMap:
        name: log-config
        items: 
          - key: log_level
            path: log_level

